from __future__ import annotations
import re
from backend.services.source_registry import SOURCE_REGISTRY
TRUSTED_SOURCES=SOURCE_REGISTRY

I18N={
'en':{'report':'News Verification Report','result':'Verification result','confidence':'Decision confidence','case_id':'Case ID','evidence_strength':'Evidence strength','generated':'Generated','claim':'Submitted claim','reasoning':'Verification summary','method':'Verification Method','evidence':'Evidence reviewed','trusted':'Trusted / fact-check sources','general':'Reputable news / related sources','unverified':'Unverified / low-credibility sources','source_quality':'Source quality','relation':'Evidence relation','support':'Supports','contradict':'Contradicts','neutral':'Neutral','not_available':'Not available','decision_basis':'Decision basis','trusted_total':'Trusted sources checked','trusted_supporting':'Trusted sources supporting','trusted_contradicting':'Trusted sources contradicting','trusted_neutral':'Trusted sources neutral','related_total':'Related sources reviewed','image_status':'Image verification status','human_note':'Decision confidence reflects the strength of the retrieved evidence. It is not a calibrated probability of truth.','consensus':'Independent trusted-source consensus','conflict':'Trusted-source conflict','insufficient':'Insufficient trusted evidence','single_support':'Only one trusted source supports the claim','image_not_provided':'No image was supplied.','image_no_reference':'No reference match was found. This does not prove that the image is authentic.','image_live':'Live visual search returned results; this is contextual evidence, not proof of authenticity.'},
'hi':{'report':'समाचार सत्यापन रिपोर्ट','result':'सत्यापन परिणाम','confidence':'निर्णय विश्वसनीयता','case_id':'केस आईडी','evidence_strength':'साक्ष्य की मजबूती','generated':'तैयार किया गया','claim':'प्रस्तुत दावा','reasoning':'सत्यापन सारांश','method':'सत्यापन विधि','evidence':'जाँचे गए साक्ष्य','trusted':'विश्वसनीय / तथ्य-जाँच स्रोत','general':'प्रतिष्ठित समाचार / संबंधित स्रोत','unverified':'असत्यापित / कम विश्वसनीय स्रोत','source_quality':'स्रोत गुणवत्ता','relation':'साक्ष्य संबंध','support':'समर्थन','contradict':'खंडन','neutral':'तटस्थ','not_available':'उपलब्ध नहीं','decision_basis':'निर्णय का आधार','trusted_total':'जाँचे गए विश्वसनीय स्रोत','trusted_supporting':'समर्थन करने वाले विश्वसनीय स्रोत','trusted_contradicting':'खंडन करने वाले विश्वसनीय स्रोत','trusted_neutral':'तटस्थ विश्वसनीय स्रोत','related_total':'समीक्षित संबंधित स्रोत','image_status':'इमेज सत्यापन स्थिति','human_note':'निर्णय विश्वसनीयता मिले हुए साक्ष्यों की मजबूती बताती है। यह सत्य की कैलिब्रेटेड संभावना नहीं है।','consensus':'स्वतंत्र विश्वसनीय स्रोतों की सहमति','conflict':'विश्वसनीय स्रोतों में विरोध','insufficient':'पर्याप्त विश्वसनीय साक्ष्य नहीं','single_support':'केवल एक विश्वसनीय स्रोत समर्थन करता है','image_not_provided':'कोई इमेज नहीं दी गई।','image_no_reference':'कोई संदर्भ मिलान नहीं मिला। इससे इमेज के असली होने का प्रमाण नहीं मिलता।','image_live':'लाइव विज़ुअल खोज में परिणाम मिले; यह संदर्भ साक्ष्य है, प्रामाणिकता का प्रमाण नहीं।'},
'ta':{'report':'செய்தி சரிபார்ப்பு அறிக்கை','result':'சரிபார்ப்பு முடிவு','confidence':'முடிவு நம்பிக்கை','case_id':'வழக்கு ID','evidence_strength':'ஆதார வலிமை','generated':'உருவாக்கப்பட்டது','claim':'சமர்ப்பிக்கப்பட்ட கூற்று','reasoning':'சரிபார்ப்பு சுருக்கம்','method':'சரிபார்ப்பு முறை','evidence':'ஆய்வு செய்யப்பட்ட ஆதாரங்கள்','trusted':'நம்பகமான / உண்மைச் சரிபார்ப்பு ஆதாரங்கள்','general':'நம்பகமான செய்தி / தொடர்புடைய ஆதாரங்கள்','unverified':'சரிபார்க்கப்படாத / குறைந்த நம்பகத்தன்மை ஆதாரங்கள்','source_quality':'ஆதார தரம்','relation':'ஆதார உறவு','support':'ஆதரவு','contradict':'முரண்பாடு','neutral':'நடுநிலை','not_available':'கிடைக்கவில்லை','decision_basis':'முடிவின் அடிப்படை','trusted_total':'சரிபார்க்கப்பட்ட நம்பகமான ஆதாரங்கள்','trusted_supporting':'ஆதரிக்கும் நம்பகமான ஆதாரங்கள்','trusted_contradicting':'முரண்படும் நம்பகமான ஆதாரங்கள்','trusted_neutral':'நடுநிலை நம்பகமான ஆதாரங்கள்','related_total':'ஆய்வு செய்யப்பட்ட தொடர்புடைய ஆதாரங்கள்','image_status':'பட சரிபார்ப்பு நிலை','human_note':'முடிவு நம்பிக்கை கிடைத்த ஆதாரங்களின் வலிமையை குறிக்கிறது. அது உண்மையின் அளவிடப்பட்ட நிகழ்தகவு அல்ல.','consensus':'சுயாதீன நம்பகமான ஆதார ஒற்றுமை','conflict':'நம்பகமான ஆதார முரண்பாடு','insufficient':'போதுமான நம்பகமான ஆதாரம் இல்லை','single_support':'ஒரே ஒரு நம்பகமான ஆதாரம் மட்டுமே ஆதரிக்கிறது','image_not_provided':'படம் வழங்கப்படவில்லை.','image_no_reference':'குறிப்பு படம் பொருந்தவில்லை. இதனால் படம் உண்மையானது என்று நிரூபிக்க முடியாது.','image_live':'நேரடி காட்சி தேடலில் முடிவுகள் கிடைத்தன; இது சூழல் ஆதாரம் மட்டுமே.'},
'bn':{'report':'সংবাদ যাচাই প্রতিবেদন','result':'যাচাইয়ের ফলাফল','confidence':'সিদ্ধান্তের নির্ভরযোগ্যতা','case_id':'কেস আইডি','evidence_strength':'প্রমাণের শক্তি','generated':'তৈরি হয়েছে','claim':'জমা দেওয়া দাবি','reasoning':'যাচাইয়ের সারাংশ','method':'যাচাই পদ্ধতি','evidence':'পর্যালোচিত প্রমাণ','trusted':'বিশ্বস্ত / ফ্যাক্ট-চেক উৎস','general':'বিশ্বস্ত সংবাদ / সম্পর্কিত উৎস','unverified':'যাচাইহীন / কম নির্ভরযোগ্য উৎস','source_quality':'উৎসের মান','relation':'প্রমাণের সম্পর্ক','support':'সমর্থন','contradict':'খণ্ডন','neutral':'নিরপেক্ষ','not_available':'পাওয়া যায়নি','decision_basis':'সিদ্ধান্তের ভিত্তি','trusted_total':'পরীক্ষিত বিশ্বস্ত উৎস','trusted_supporting':'সমর্থনকারী বিশ্বস্ত উৎস','trusted_contradicting':'খণ্ডনকারী বিশ্বস্ত উৎস','trusted_neutral':'নিরপেক্ষ বিশ্বস্ত উৎস','related_total':'পর্যালোচিত সম্পর্কিত উৎস','image_status':'ছবি যাচাইয়ের অবস্থা','human_note':'সিদ্ধান্তের নির্ভরযোগ্যতা প্রাপ্ত প্রমাণের শক্তি বোঝায়; এটি সত্যতার ক্যালিব্রেটেড সম্ভাবনা নয়।','consensus':'স্বাধীন বিশ্বস্ত উৎসের ঐকমত্য','conflict':'বিশ্বস্ত উৎসের বিরোধ','insufficient':'পর্যাপ্ত বিশ্বস্ত প্রমাণ নেই','single_support':'শুধু একটি বিশ্বস্ত উৎস সমর্থন করছে','image_not_provided':'কোনও ছবি দেওয়া হয়নি।','image_no_reference':'কোনও রেফারেন্স মিল পাওয়া যায়নি। এতে ছবিটি আসল প্রমাণ হয় না।','image_live':'লাইভ ভিজ্যুয়াল অনুসন্ধানে ফল পাওয়া গেছে; এটি প্রামাণিকতার প্রমাণ নয়।'},
'te':{'report':'వార్తా ధృవీకరణ నివేదిక','result':'ధృవీకరణ ఫలితం','confidence':'నిర్ణయ నమ్మకం','case_id':'కేసు ID','evidence_strength':'ఆధార బలం','generated':'రూపొందించబడింది','claim':'సమర్పించిన దావా','reasoning':'ధృవీకరణ సారాంశం','method':'ధృవీకరణ విధానం','evidence':'పరిశీలించిన ఆధారాలు','trusted':'విశ్వసనీయ / ఫ్యాక్ట్-చెక్ మూలాలు','general':'ప్రతిష్ఠాత్మక వార్త / సంబంధిత మూలాలు','unverified':'ధృవీకరించని / తక్కువ విశ్వసనీయ మూలాలు','source_quality':'మూల నాణ్యత','relation':'ఆధార సంబంధం','support':'మద్దతు','contradict':'విరుద్ధం','neutral':'తటస్థం','not_available':'అందుబాటులో లేదు','decision_basis':'నిర్ణయ ఆధారం','trusted_total':'పరిశీలించిన విశ్వసనీయ మూలాలు','trusted_supporting':'మద్దతిచ్చే విశ్వసనీయ మూలాలు','trusted_contradicting':'విరుద్ధమైన విశ్వసనీయ మూలాలు','trusted_neutral':'తటస్థ విశ్వసనీయ మూలాలు','related_total':'పరిశీలించిన సంబంధిత మూలాలు','image_status':'చిత్ర ధృవీకరణ స్థితి','human_note':'నిర్ణయ నమ్మకం అందుబాటులో ఉన్న ఆధారాల బలాన్ని సూచిస్తుంది; ఇది నిజం యొక్క కేలిబ్రేట్ చేసిన సంభావ్యత కాదు.','consensus':'స్వతంత్ర విశ్వసనీయ మూలాల ఏకాభిప్రాయం','conflict':'విశ్వసనీయ మూలాల విరుద్ధం','insufficient':'తగిన విశ్వసనీయ ఆధారం లేదు','single_support':'ఒక్క విశ్వసనీయ మూలం మాత్రమే మద్దతిస్తోంది','image_not_provided':'చిత్రం ఇవ్వలేదు.','image_no_reference':'రిఫరెన్స్ చిత్రం సరిపోలలేదు. ఇది చిత్రం అసలైనదని నిరూపించదు.','image_live':'లైవ్ విజువల్ శోధనలో ఫలితాలు వచ్చాయి; ఇది ప్రామాణికతకు రుజువు కాదు.'},
'mr':{'report':'बातमी पडताळणी अहवाल','result':'पडताळणी निकाल','confidence':'निर्णयाचा विश्वास','case_id':'केस आयडी','evidence_strength':'पुराव्याची ताकद','generated':'तयार केले','claim':'सादर केलेला दावा','reasoning':'पडताळणी सारांश','method':'पडताळणी पद्धत','evidence':'तपासलेले पुरावे','trusted':'विश्वसनीय / तथ्य-पडताळणी स्रोत','general':'प्रतिष्ठित बातम्या / संबंधित स्रोत','unverified':'अपडताळलेले / कमी विश्वासार्ह स्रोत','source_quality':'स्रोत गुणवत्ता','relation':'पुराव्याचा संबंध','support':'समर्थन','contradict':'विरोध','neutral':'तटस्थ','not_available':'उपलब्ध नाही','decision_basis':'निर्णयाचा आधार','trusted_total':'तपासलेले विश्वसनीय स्रोत','trusted_supporting':'समर्थन करणारे विश्वसनीय स्रोत','trusted_contradicting':'विरोध करणारे विश्वसनीय स्रोत','trusted_neutral':'तटस्थ विश्वसनीय स्रोत','related_total':'तपासलेले संबंधित स्रोत','image_status':'प्रतिमा पडताळणी स्थिती','human_note':'निर्णयाचा विश्वास उपलब्ध पुराव्याची ताकद दर्शवतो; तो सत्याची कॅलिब्रेटेड शक्यता नाही.','consensus':'स्वतंत्र विश्वसनीय स्रोतांची एकमतता','conflict':'विश्वसनीय स्रोतांमध्ये विरोध','insufficient':'पुरेसा विश्वसनीय पुरावा नाही','single_support':'फक्त एक विश्वसनीय स्रोत समर्थन करतो','image_not_provided':'प्रतिमा दिलेली नाही.','image_no_reference':'संदर्भ प्रतिमा जुळली नाही. यामुळे प्रतिमा खरी असल्याचे सिद्ध होत नाही.','image_live':'लाइव्ह दृश्य शोधात परिणाम मिळाले; हे प्रामाणिकतेचा पुरावा नाही.'},
'gu':{'report':'સમાચાર ચકાસણી અહેવાલ','result':'ચકાસણી પરિણામ','confidence':'નિર્ણય વિશ્વાસ','case_id':'કેસ ID','evidence_strength':'પુરાવાની મજબૂતી','generated':'તૈયાર કરાયેલ','claim':'રજૂ કરાયેલ દાવો','reasoning':'ચકાસણી સારાંશ','method':'ચકાસણી પદ્ધતિ','evidence':'ચકાસેલા પુરાવા','trusted':'વિશ્વસનીય / ફેક્ટ-ચેક સ્ત્રોતો','general':'પ્રતિષ્ઠિત સમાચાર / સંબંધિત સ્ત્રોતો','unverified':'ચકાસ્યા વિનાના / ઓછા વિશ્વસનીય સ્ત્રોતો','source_quality':'સ્ત્રોત ગુણવત્તા','relation':'પુરાવાનો સંબંધ','support':'સમર્થન','contradict':'વિરોધ','neutral':'તટસ્થ','not_available':'ઉપલબ્ધ નથી','decision_basis':'નિર્ણયનો આધાર','trusted_total':'ચકાસેલા વિશ્વસનીય સ્ત્રોતો','trusted_supporting':'સમર્થન કરતા વિશ્વસનીય સ્ત્રોતો','trusted_contradicting':'વિરોધ કરતા વિશ્વસનીય સ્ત્રોતો','trusted_neutral':'તટસ્થ વિશ્વસનીય સ્ત્રોતો','related_total':'ચકાસેલા સંબંધિત સ્ત્રોતો','image_status':'છબી ચકાસણી સ્થિતિ','human_note':'નિર્ણય વિશ્વાસ ઉપલબ્ધ પુરાવાની મજબૂતી દર્શાવે છે; તે સત્યની માપેલી સંભાવના નથી.','consensus':'સ્વતંત્ર વિશ્વસનીય સ્ત્રોતોની સહમતિ','conflict':'વિશ્વસનીય સ્ત્રોતોમાં વિરોધ','insufficient':'પૂરતો વિશ્વસનીય પુરાવો નથી','single_support':'માત્ર એક વિશ્વસનીય સ્ત્રોત સમર્થન કરે છે','image_not_provided':'છબી આપવામાં આવી નથી.','image_no_reference':'સંદર્ભ છબી મળી નથી. આથી છબી અસલી છે તે સાબિત થતું નથી.','image_live':'લાઇવ દૃશ્ય શોધમાં પરિણામો મળ્યા; આ પ્રામાણિકતાનો પુરાવો નથી.'},
'kn':{'report':'ಸುದ್ದಿ ಪರಿಶೀಲನಾ ವರದಿ','result':'ಪರಿಶೀಲನಾ ಫಲಿತಾಂಶ','confidence':'ನಿರ್ಣಯ ವಿಶ್ವಾಸ','case_id':'ಕೇಸ್ ID','evidence_strength':'ಸಾಕ್ಷ್ಯದ ಬಲ','generated':'ರಚಿಸಲಾಗಿದೆ','claim':'ಸಲ್ಲಿಸಿದ ದಾವೆ','reasoning':'ಪರಿಶೀಲನಾ ಸಾರಾಂಶ','method':'ಪರಿಶೀಲನಾ ವಿಧಾನ','evidence':'ಪರಿಶೀಲಿಸಿದ ಸಾಕ್ಷ್ಯಗಳು','trusted':'ವಿಶ್ವಾಸಾರ್ಹ / ಫ್ಯಾಕ್ಟ್-ಚೆಕ್ ಮೂಲಗಳು','general':'ಪ್ರತಿಷ್ಠಿತ ಸುದ್ದಿ / ಸಂಬಂಧಿತ ಮೂಲಗಳು','unverified':'ಪರಿಶೀಲಿಸದ / ಕಡಿಮೆ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳು','source_quality':'ಮೂಲ ಗುಣಮಟ್ಟ','relation':'ಸಾಕ್ಷ್ಯದ ಸಂಬಂಧ','support':'ಬೆಂಬಲ','contradict':'ವಿರೋಧ','neutral':'ತಟಸ್ಥ','not_available':'ಲಭ್ಯವಿಲ್ಲ','decision_basis':'ನಿರ್ಣಯದ ಆಧಾರ','trusted_total':'ಪರಿಶೀಲಿಸಿದ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳು','trusted_supporting':'ಬೆಂಬಲಿಸುವ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳು','trusted_contradicting':'ವಿರೋಧಿಸುವ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳು','trusted_neutral':'ತಟಸ್ಥ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳು','related_total':'ಪರಿಶೀಲಿಸಿದ ಸಂಬಂಧಿತ ಮೂಲಗಳು','image_status':'ಚಿತ್ರ ಪರಿಶೀಲನಾ ಸ್ಥಿತಿ','human_note':'ನಿರ್ಣಯ ವಿಶ್ವಾಸವು ಲಭ್ಯವಿರುವ ಸಾಕ್ಷ್ಯದ ಬಲವನ್ನು ಸೂಚಿಸುತ್ತದೆ; ಇದು ಸತ್ಯದ ಅಳತೆಯ ಸಾಧ್ಯತೆ ಅಲ್ಲ.','consensus':'ಸ್ವತಂತ್ರ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳ ಒಮ್ಮತ','conflict':'ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲಗಳ ವಿರೋಧ','insufficient':'ಸಾಕಷ್ಟು ವಿಶ್ವಾಸಾರ್ಹ ಸಾಕ್ಷ್ಯವಿಲ್ಲ','single_support':'ಒಂದು ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲ ಮಾತ್ರ ಬೆಂಬಲಿಸುತ್ತದೆ','image_not_provided':'ಚಿತ್ರ ನೀಡಲಾಗಿಲ್ಲ.','image_no_reference':'ಉಲ್ಲೇಖ ಚಿತ್ರ ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ. ಇದರಿಂದ ಚಿತ್ರ ನಿಜವೆಂದು ಸಾಬೀತಾಗುವುದಿಲ್ಲ.','image_live':'ಲೈವ್ ದೃಶ್ಯ ಹುಡುಕಾಟದಲ್ಲಿ ಫಲಿತಾಂಶಗಳು ಬಂದಿವೆ; ಇದು ಪ್ರಾಮಾಣಿಕತೆಯ ಪುರಾವೆ ಅಲ್ಲ.'},
'ml':{'report':'വാർത്താ പരിശോധന റിപ്പോർട്ട്','result':'പരിശോധന ഫലം','confidence':'തീരുമാന വിശ്വാസം','case_id':'കേസ് ID','evidence_strength':'തെളിവിന്റെ ശക്തി','generated':'തയ്യാറാക്കിയത്','claim':'സമർപ്പിച്ച അവകാശവാദം','reasoning':'പരിശോധന സംഗ്രഹം','method':'പരിശോധന രീതി','evidence':'പരിശോധിച്ച തെളിവുകൾ','trusted':'വിശ്വസനീയ / ഫാക്ട്-ചെക്ക് ഉറവിടങ്ങൾ','general':'പ്രശസ്ത വാർത്ത / ബന്ധപ്പെട്ട ഉറവിടങ്ങൾ','unverified':'സ്ഥിരീകരിക്കാത്ത / കുറഞ്ഞ വിശ്വാസ്യതയുള്ള ഉറവിടങ്ങൾ','source_quality':'ഉറവിട ഗുണമേന്മ','relation':'തെളിവിന്റെ ബന്ധം','support':'പിന്തുണ','contradict':'വിരോധം','neutral':'നിഷ്പക്ഷം','not_available':'ലഭ്യമല്ല','decision_basis':'തീരുമാനത്തിന്റെ അടിസ്ഥാനം','trusted_total':'പരിശോധിച്ച വിശ്വസനീയ ഉറവിടങ്ങൾ','trusted_supporting':'പിന്തുണയ്ക്കുന്ന വിശ്വസനീയ ഉറവിടങ്ങൾ','trusted_contradicting':'വിരോധിക്കുന്ന വിശ്വസനീയ ഉറവിടങ്ങൾ','trusted_neutral':'നിഷ്പക്ഷ വിശ്വസനീയ ഉറവിടങ്ങൾ','related_total':'പരിശോധിച്ച ബന്ധപ്പെട്ട ഉറവിടങ്ങൾ','image_status':'ചിത്ര പരിശോധന നില','human_note':'തീരുമാന വിശ്വാസം ലഭ്യമായ തെളിവുകളുടെ ശക്തി സൂചിപ്പിക്കുന്നു; ഇത് സത്യത്തിന്റെ കൃത്യമായ സാധ്യതയല്ല.','consensus':'സ്വതന്ത്ര വിശ്വസനീയ ഉറവിടങ്ങളുടെ ഏകാഭിപ്രായം','conflict':'വിശ്വസനീയ ഉറവിടങ്ങളുടെ വിരോധം','insufficient':'മതിയായ വിശ്വസനീയ തെളിവില്ല','single_support':'ഒരു വിശ്വസനീയ ഉറവിടം മാത്രം പിന്തുണയ്ക്കുന്നു','image_not_provided':'ചിത്രം നൽകിയിട്ടില്ല.','image_no_reference':'റഫറൻസ് ചിത്രം പൊരുത്തപ്പെട്ടില്ല. ചിത്രം യഥാർത്ഥമാണെന്ന് ഇത് തെളിയിക്കുന്നില്ല.','image_live':'ലൈവ് വിഷ്വൽ തിരച്ചിലിൽ ഫലങ്ങൾ ലഭിച്ചു; ഇത് പ്രാമാണികതയുടെ തെളിവല്ല.'},
'pa':{'report':'ਖ਼ਬਰ ਜਾਂਚ ਰਿਪੋਰਟ','result':'ਜਾਂਚ ਨਤੀਜਾ','confidence':'ਫੈਸਲੇ ਦਾ ਭਰੋਸਾ','case_id':'ਕੇਸ ID','evidence_strength':'ਸਬੂਤ ਦੀ ਮਜ਼ਬੂਤੀ','generated':'ਤਿਆਰ ਕੀਤਾ ਗਿਆ','claim':'ਪੇਸ਼ ਕੀਤਾ ਦਾਅਵਾ','reasoning':'ਜਾਂਚ ਸਾਰ','method':'ਜਾਂਚ ਵਿਧੀ','evidence':'ਜਾਂਚੇ ਗਏ ਸਬੂਤ','trusted':'ਭਰੋਸੇਯੋਗ / ਫੈਕਟ-ਚੈਕ ਸਰੋਤ','general':'ਮਾਣਯੋਗ ਖ਼ਬਰਾਂ / ਸੰਬੰਧਿਤ ਸਰੋਤ','unverified':'ਅਪ੍ਰਮਾਣਿਤ / ਘੱਟ ਭਰੋਸੇਯੋਗ ਸਰੋਤ','source_quality':'ਸਰੋਤ ਗੁਣਵੱਤਾ','relation':'ਸਬੂਤ ਸੰਬੰਧ','support':'ਸਮਰਥਨ','contradict':'ਵਿਰੋਧ','neutral':'ਤਟਸਥ','not_available':'ਉਪਲਬਧ ਨਹੀਂ','decision_basis':'ਫੈਸਲੇ ਦਾ ਆਧਾਰ','trusted_total':'ਜਾਂਚੇ ਭਰੋਸੇਯੋਗ ਸਰੋਤ','trusted_supporting':'ਸਮਰਥਨ ਕਰਨ ਵਾਲੇ ਭਰੋਸੇਯੋਗ ਸਰੋਤ','trusted_contradicting':'ਵਿਰੋਧ ਕਰਨ ਵਾਲੇ ਭਰੋਸੇਯੋਗ ਸਰੋਤ','trusted_neutral':'ਤਟਸਥ ਭਰੋਸੇਯੋਗ ਸਰੋਤ','related_total':'ਜਾਂਚੇ ਸੰਬੰਧਿਤ ਸਰੋਤ','image_status':'ਤਸਵੀਰ ਜਾਂਚ ਸਥਿਤੀ','human_note':'ਫੈਸਲੇ ਦਾ ਭਰੋਸਾ ਮਿਲੇ ਸਬੂਤ ਦੀ ਮਜ਼ਬੂਤੀ ਦੱਸਦਾ ਹੈ; ਇਹ ਸੱਚ ਦੀ ਮਾਪੀ ਹੋਈ ਸੰਭਾਵਨਾ ਨਹੀਂ ਹੈ।','consensus':'ਸੁਤੰਤਰ ਭਰੋਸੇਯੋਗ ਸਰੋਤਾਂ ਦੀ ਸਹਿਮਤੀ','conflict':'ਭਰੋਸੇਯੋਗ ਸਰੋਤਾਂ ਵਿੱਚ ਵਿਰੋਧ','insufficient':'ਕਾਫ਼ੀ ਭਰੋਸੇਯੋਗ ਸਬੂਤ ਨਹੀਂ','single_support':'ਸਿਰਫ਼ ਇੱਕ ਭਰੋਸੇਯੋਗ ਸਰੋਤ ਸਮਰਥਨ ਕਰਦਾ ਹੈ','image_not_provided':'ਕੋਈ ਤਸਵੀਰ ਨਹੀਂ ਦਿੱਤੀ ਗਈ।','image_no_reference':'ਕੋਈ ਹਵਾਲਾ ਤਸਵੀਰ ਨਹੀਂ ਮਿਲੀ। ਇਸ ਨਾਲ ਤਸਵੀਰ ਦੇ ਅਸਲੀ ਹੋਣ ਦਾ ਸਬੂਤ ਨਹੀਂ ਮਿਲਦਾ।','image_live':'ਲਾਈਵ ਵਿਜ਼ੂਅਲ ਖੋਜ ਵਿੱਚ ਨਤੀਜੇ ਮਿਲੇ; ਇਹ ਪ੍ਰਮਾਣਿਕਤਾ ਦਾ ਸਬੂਤ ਨਹੀਂ ਹੈ.'}
}

for lang in ('en','hi','ta','bn','te','mr','gu','kn','ml','pa'):
    I18N.setdefault(lang,{})
    for k,v in I18N['en'].items(): I18N[lang].setdefault(k,v)

def tr(language,key): return I18N.get(language,I18N['en']).get(key,I18N['en'].get(key,key))

def normalize_confidence(value):
    try: value=float(value)
    except (TypeError,ValueError): return 0.0
    if 0<=value<=1: value*=100
    return round(max(0.0,min(100.0,value)),2)

def classify_source(url,score=None):
    from urllib.parse import urlparse
    host=(urlparse(str(url or '')).hostname or '').lower()
    try: score=float(score)
    except (TypeError,ValueError): score=0.35
    # Use the same source registry as the retriever, but keep compatibility with old report data.
    for group in ('trusted_india','trusted_international'):
        for item in TRUSTED_SOURCES.get(group,[]) if isinstance(TRUSTED_SOURCES,dict) else []:
            d=item.get('domain','') if isinstance(item,dict) else ''
            if d and (host==d or host.endswith('.'+d)): return {'category':'trusted','quality':'High','score':item.get('score',0.9),'name':item.get('name',d),'group':group}
    if score>=.75: return {'category':'general','quality':'Moderate','score':score,'name':host,'group':''}
    if score>=.55: return {'category':'general','quality':'Low','score':score,'name':host,'group':''}
    return {'category':'unverified','quality':'Very low','score':score,'name':host,'group':''}

def normalize_relation(value):
    value=str(value or '').upper().strip()
    value={'ENTAILED':'SUPPORTS','SUPPORTED':'SUPPORTS','SUPPORT':'SUPPORTS','CONTRADICTED':'CONTRADICTS','CONTRADICTION':'CONTRADICTS','CONTRADICT':'CONTRADICTS'}.get(value,value)
    return value if value in {'SUPPORTS','CONTRADICTS'} else 'NEUTRAL'

def normalize_evidence(items):
    if not isinstance(items,list): return []
    out=[]
    for item in items:
        if isinstance(item,str):
            m=re.search(r'https?://\S+',item); url=m.group(0) if m else ''
            out.append({'title':item[:220],'url':url,'relation':'NEUTRAL','source_quality':classify_source(url)})
        elif isinstance(item,dict):
            url=item.get('url') or item.get('link') or ''; sq=item.get('source_quality') or classify_source(url,item.get('credibility') if item.get('credibility') is not None else item.get('score'))
            out.append({**item,'url':url,'relation':normalize_relation(item.get('relation') or item.get('stance') or item.get('label')),'source_quality':sq})
    return out

def clean_reasoning(result,language):
    text=str(result.get('localized_reasoning') or result.get('reasoning') or result.get('summary') or '').strip()
    bad=('local llm unavailable','deterministic evidence-weighted fallback used','local language model was unavailable')
    if text and not any(x in text.lower() for x in bad): return text
    evidence=normalize_evidence(result.get('evidence') or result.get('sources') or [])
    s=sum(x['relation']=='SUPPORTS' for x in evidence); c=sum(x['relation']=='CONTRADICTS' for x in evidence)
    if language=='hi': return f'उपलब्ध साक्ष्यों में {s} स्रोत समर्थन और {c} स्रोत खंडन करते हैं। निष्कर्ष केवल समान दावे से सीधे संबंधित साक्ष्य और स्रोत गुणवत्ता पर आधारित है।'
    if language=='ta': return f'கிடைத்த ஆதாரங்களில் {s} ஆதாரங்கள் ஆதரிக்கின்றன; {c} ஆதாரங்கள் முரண்படுகின்றன. முடிவு அதே கூற்றுடன் நேரடியாக தொடர்புடைய ஆதாரம் மற்றும் ஆதாரத் தரத்தை அடிப்படையாகக் கொண்டது.'
    return f'{s} reviewed source(s) support the claim and {c} contradict it. The decision uses evidence that directly matches the same claim and source quality.'

def method_text(result,language):
    fetched=bool(result.get('article_fetched'))
    status=str(result.get('llm_status') or '').upper(); provider=str(result.get('provider','')).lower()
    if language=='hi':
        return ('लाइव वेब स्रोत, समान-दावे मिलान, स्रोत गुणवत्ता, स्वतंत्र स्रोत सहमति और इमेज संदर्भ की जाँच की गई।' if fetched else 'लाइव वेब स्रोत, समान-दावे मिलान, स्रोत गुणवत्ता, स्वतंत्र स्रोत सहमति और इमेज संदर्भ की जाँच की गई।') + ((' स्थानीय भाषा मॉडल का उपयोग केवल व्याख्या के लिए किया गया।' if status=='OK' or provider=='ollama' else ' स्थानीय भाषा मॉडल उपलब्ध न होने पर निर्धारक साक्ष्य नियम लागू किए गए।'))
    if language=='ta': return 'நேரடி வலை ஆதாரங்கள், அதே கூற்று பொருத்தம், ஆதார தரம், சுயாதீன ஆதார ஒற்றுமை மற்றும் பட சூழல் சரிபார்க்கப்பட்டது.'
    if language=='bn': return 'লাইভ ওয়েব উৎস, একই দাবির মিল, উৎসের মান, স্বাধীন উৎসের ঐকমত্য এবং ছবির প্রাসঙ্গিকতা পরীক্ষা করা হয়েছে।'
    if language=='te': return 'లైవ్ వెబ్ మూలాలు, అదే దావా సరిపోలిక, మూల నాణ్యత, స్వతంత్ర మూలాల ఏకాభిప్రాయం మరియు చిత్ర సందర్భం పరిశీలించబడింది.'
    if language=='mr': return 'लाइव्ह वेब स्रोत, समान दाव्याचे जुळणे, स्रोत गुणवत्ता, स्वतंत्र स्रोतांची एकमतता आणि प्रतिमा संदर्भ तपासला गेला.'
    if language=='gu': return 'લાઇવ વેબ સ્ત્રોતો, સમાન દાવાનું મેચિંગ, સ્ત્રોત ગુણવત્તા, સ્વતંત્ર સ્ત્રોતોની સહમતિ અને છબી સંદર્ભ તપાસવામાં આવ્યો.'
    if language=='kn': return 'ಲೈವ್ ವೆಬ್ ಮೂಲಗಳು, ಅದೇ ದಾವೆಯ ಹೊಂದಾಣಿಕೆ, ಮೂಲ ಗುಣಮಟ್ಟ, ಸ್ವತಂತ್ರ ಮೂಲಗಳ ಒಮ್ಮತ ಮತ್ತು ಚಿತ್ರ ಸಂದರ್ಭವನ್ನು ಪರಿಶೀಲಿಸಲಾಗಿದೆ.'
    if language=='ml': return 'ലൈവ് വെബ് ഉറവിടങ്ങൾ, അതേ അവകാശവാദ പൊരുത്തം, ഉറവിട ഗുണമേന്മ, സ്വതന്ത്ര ഉറവിടങ്ങളുടെ ഏകാഭിപ്രായം, ചിത്രത്തിന്റെ പശ്ചാത്തലം എന്നിവ പരിശോധിച്ചു.'
    if language=='pa': return 'ਲਾਈਵ ਵੈੱਬ ਸਰੋਤ, ਉਸੇ ਦਾਅਵੇ ਦੀ ਮਿਲਾਣ, ਸਰੋਤ ਗੁਣਵੱਤਾ, ਸੁਤੰਤਰ ਸਰੋਤਾਂ ਦੀ ਸਹਿਮਤੀ ਅਤੇ ਤਸਵੀਰ ਦਾ ਸੰਦਰਭ ਜਾਂਚਿਆ ਗਿਆ।'
    return 'Live web sources, same-claim matching, source quality, independent-source agreement and image context were checked.'
