const $=id=>document.getElementById(id);
const T=window.ALETHEIA_TRANSLATIONS||{};
const language=$('language'),claim=$('claim'),articleUrl=$('articleUrl'),imageUrl=$('imageUrl'),verifyBtn=$('verifyBtn'),historyBtn=$('historyBtn'),closeHistory=$('closeHistory'),historyList=$('historyList'),caseSearch=$('caseSearch'),progress=$('progress'),progressBar=$('progressBar'),progressText=$('progressText'),result=$('result'),resultVerdict=$('resultVerdict'),confidenceValue=$('confidenceValue'),reasoning=$('reasoning'),evidenceStrength=$('evidenceStrength'),caseId=$('caseId'),evidenceList=$('evidenceList'),imageResult=$('imageResult'),downloadReport=$('downloadReport'),openReport=$('openReport'),decisionSummary=$('decisionSummary'),method=$('verificationMethod');
function t(k){const l=language.value||'en';return(T[l]&&T[l][k])||(T.en&&T.en[k])||k)}
function verdictText(v){return t(String(v||'UNVERIFIED').toLowerCase())}
function percent(v){let n=Number(v);if(!Number.isFinite(n))return 0;if(n>=0&&n<=1)n*=100;return Math.max(0,Math.min(100,n))}
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function translateStaticUI(){document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));document.documentElement.lang=language.value||'en'}
function initLanguages(){language.innerHTML=Object.entries(T).map(([c,d])=>`<option value="${c}">${esc(d.name)}</option>`).join('');const saved=localStorage.getItem('aletheia-language');language.value=saved&&T[saved]?saved:'en';translateStaticUI()}
function setProgress(v,key,step){progress.classList.remove('hidden');const p=Math.round(Math.max(0,Math.min(100,v)));progressBar.style.width=`${p}%`;progressText.textContent=`${p}% · ${t(key)}`;document.querySelectorAll('.steps div').forEach(n=>n.classList.toggle('active',n.dataset.step===step))}
function resultObject(d){return d&&typeof d.result==='object'?d.result:d}
function renderDecision(item){const s=item.decision_summary||{};const rows=[[t('trusted_total'),s.trusted_total??item.trusted_source_count??0],[t('trusted_supporting'),s.trusted_supporting??item.trusted_supporting_count??0],[t('trusted_contradicting'),s.trusted_contradicting??item.trusted_contradicting_count??0],[t('trusted_neutral'),s.trusted_neutral??item.trusted_neutral_count??0],[t('related_total'),s.related_total??item.related_source_count??0]];decisionSummary.innerHTML=rows.map(r=>`<div class="decision-row"><span>${esc(r[0])}</span><strong>${esc(r[1])}</strong></div>`).join('')+`<div class="decision-basis">${esc(t('decision_basis'))}: <strong>${esc(String(s.basis||item.decision_basis||'').replaceAll('_',' '))}</strong></div>`}
function evidenceGroup(i){const tier=String(i.tier||'general').toLowerCase();if(['primary','fact_check'].includes(tier))return'trusted';if(tier==='reputable_news')return'other';const cat=String(i.source_quality?.category||'').toUpperCase();return cat.includes('UNVERIFIED')?'unverified':'other'}
function renderEvidence(items){if(!Array.isArray(items)||!items.length){evidenceList.innerHTML=`<p class="muted">${esc(t('no_cases'))}</p>`;return}const groups={trusted:[],other:[],unverified:[]};items.forEach(i=>groups[evidenceGroup(i)].push(i));const group=(title,rows)=>!rows.length?'':`<div class="evidence-group"><h4>${esc(title)} <span>(${rows.length})</span></h4>${rows.map((i,n)=>{const title=i.title||i.source_name||i.source||i.name||`${t('evidence_reviewed')} ${n+1}`;const rel=i.relation||'NEUTRAL';const reltxt=rel==='SUPPORTS'?t('supports'):rel==='CONTRADICTS'?t('contradicts'):t('neutral');const tier=i.tier||'';const url=i.url||'';const snippet=String(i.content||i.snippet||'').replace(/\s+/g,' ').slice(0,360);return`<div class="evidence-item"><div class="evidence-title">${esc(title)}</div><div class="evidence-meta">${esc(t('relation'))}: ${esc(reltxt)} · ${esc(tier)}</div>${snippet?`<div class="evidence-snippet">${esc(snippet)}</div>`:''}${url?`<a class="evidence-url" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(t('open_source'))}</a>`:''}</div>`}).join('')}</div>`;evidenceList.innerHTML=group(t('trusted_sources'),groups.trusted)+group(t('other_sources'),groups.other)+group(t('unverified_sources'),groups.unverified)}
function renderImage(img){if(!img)return`<p class="muted">${esc(t('image_not_provided'))}</p>`;const status=String(img.status||'UNAVAILABLE').toUpperCase();let title=t('image_no_reference');if(status==='MATCH')title=t('image_match');else if(status==='LIVE_RESULTS')title=t('image_live').replace('{n}',String(img.live_visual?.total_results||0));else if(status==='NOT_PROVIDED')title=t('image_not_provided');let html=`<div class="image-status"><strong>${esc(t('image_status_label'))}:</strong> ${esc(status)}</div><p>${esc(title)}</p>`;if(img.hash)html+=`<div class="evidence-meta">${esc(t('image_hash'))}: ${esc(img.hash)}</div>`;const sem=img.semantic_consistency;if(sem?.status)html+=`<div class="evidence-meta">${esc(t('image_semantic'))}: ${esc(sem.status)}${sem.claim_consistency!=null?` (${Number(sem.claim_consistency).toFixed(3)})`:''}</div>`;const live=img.live_visual?.results||[];if(live.length)html+=`<div class="image-live-results">${live.map(x=>x.page_url?`<a class="evidence-url" href="${esc(x.page_url)}" target="_blank" rel="noopener noreferrer">${esc(x.page_url)}</a>`:'').join('<br>')}</div>`;return html}
function renderResult(data){const i=resultObject(data),v=i.verdict||data.verdict||'UNVERIFIED',id=data.case_id||i.case_id||data._history?.case_id||'CASE-NOT-AVAILABLE';resultVerdict.textContent=verdictText(v).toUpperCase();confidenceValue.textContent=`${percent(i.confidence??data.confidence??0).toFixed(0)}%`;caseId.textContent=`${t('case_id')}: ${id}`;reasoning.textContent=i.reasoning||i.summary||data.reasoning||'';evidenceStrength.textContent=i.evidence_strength||data.evidence_strength||'—';method.textContent=i.verification_method||data.verification_method||'';renderDecision(i);renderEvidence(i.evidence||i.sources||data.evidence||data.sources||[]);const img=i.image_verification||i.image||data.image_verification;imageResult.innerHTML=renderImage(img);const report=`/api/v1/cases/${encodeURIComponent(id)}/report.pdf`;downloadReport.href=report;openReport.href=`${report}?inline=true`;result.classList.remove('hidden')}
async function verifyClaim(){const value=claim.value.trim();if(!value){alert(t('claim_required'));claim.focus();return}verifyBtn.disabled=true;result.classList.add('hidden');let running=true,current=8,ticks=0;setProgress(8,'reading','claim');const ticker=setInterval(()=>{if(!running)return;ticks++;if(current<30)current+=2;else if(current<60)current+=1;else if(current<80)current+=.5;else if(current<94)current+=.2;current=Math.min(94,current);const step=current<30?'claim':current<60?'model':current<75?'evidence':current<90?'sources':'image';setProgress(current,'progress_wait',step);if(ticks>50){progressText.textContent=`${Math.round(current)}% · (Downloading AI models on first run... please wait)`}},160);try{const r=await fetch('/api/v1/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({article:value,article_url:articleUrl.value.trim()||null,image_url:imageUrl.value.trim()||null,language:language.value})});if(!r.ok)throw new Error(await r.text()||t('verification_failed'));const d=await r.json();running=false;clearInterval(ticker);setProgress(100,'progress_final','final');renderResult(d);await loadHistory()}catch(e){running=false;clearInterval(ticker);console.error(e);alert(`${t('verification_failed')}\n\n${e.message||e}`)}finally{verifyBtn.disabled=false}}
async function loadHistory(q=''){historyList.innerHTML=`<p class="muted">${esc(t('loading'))}</p>`;try{const qs=q.trim()?`?case_id=${encodeURIComponent(q.trim())}`:'';const r=await fetch(`/api/v1/cases${qs}`);if(!r.ok)throw new Error(t('history_failed'));const items=(await r.json()).items||[];if(!items.length){historyList.innerHTML=`<p class="muted">${esc(t('no_cases'))}</p>`;return}historyList.innerHTML=items.map(i=>`<div class="history-item" data-case="${esc(i.case_id)}"><div class="history-case">${esc(i.case_id)}</div><div class="history-title">${esc((i.title||i.claim||'Untitled case').slice(0,110))}</div><div class="history-meta">${esc(verdictText(i.verdict))} · ${percent(i.confidence).toFixed(0)}%</div></div>`).join('');document.querySelectorAll('.history-item').forEach(n=>n.addEventListener('click',()=>openCase(n.dataset.case)))}catch(e){historyList.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function openCase(id){try{const r=await fetch(`/api/v1/cases/${encodeURIComponent(id)}`);if(!r.ok)throw new Error(t('case_not_found'));renderResult(await r.json());document.body.classList.remove('history-open')}catch(e){alert(e.message)}}
language.addEventListener('change',()=>{localStorage.setItem('aletheia-language',language.value);translateStaticUI();loadHistory(caseSearch.value)});caseSearch.addEventListener('input',()=>loadHistory(caseSearch.value));verifyBtn.addEventListener('click',verifyClaim);historyBtn.addEventListener('click',async()=>{document.body.classList.add('history-open');await loadHistory(caseSearch.value)});closeHistory.addEventListener('click',()=>document.body.classList.remove('history-open'));initLanguages();loadHistory();
