services:
  - type: web
    name: fakenewsdetector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_pnt48eLiKMBW@ep-spring-frost-b59xw6nh-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
